"""baseline with all tables and role

Revision ID: eb992de506b0
Revises: 
Create Date: 2026-01-28 14:38:43.390456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb992de506b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Category_category_name'), 'Category', ['category_name'], unique=True)
    op.create_index(op.f('ix_Category_id'), 'Category', ['id'], unique=False)
    op.create_table('Priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority_name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Priority_id'), 'Priority', ['id'], unique=False)
    op.create_index(op.f('ix_Priority_level'), 'Priority', ['level'], unique=False)
    op.create_index(op.f('ix_Priority_priority_name'), 'Priority', ['priority_name'], unique=True)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('Ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('Categoryid', sa.Integer(), nullable=True),
    sa.Column('Priorityid', sa.Integer(), nullable=True),
    sa.Column('Userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Categoryid'], ['Category.id'], ),
    sa.ForeignKeyConstraint(['Priorityid'], ['Priority.id'], ),
    sa.ForeignKeyConstraint(['Userid'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ticket_id'), 'Ticket', ['id'], unique=False)
    op.create_index(op.f('ix_Ticket_message'), 'Ticket', ['message'], unique=False)
    op.create_index(op.f('ix_Ticket_status'), 'Ticket', ['status'], unique=False)
    op.create_index(op.f('ix_Ticket_title'), 'Ticket', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Ticket_title'), table_name='Ticket')
    op.drop_index(op.f('ix_Ticket_status'), table_name='Ticket')
    op.drop_index(op.f('ix_Ticket_message'), table_name='Ticket')
    op.drop_index(op.f('ix_Ticket_id'), table_name='Ticket')
    op.drop_table('Ticket')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Priority_priority_name'), table_name='Priority')
    op.drop_index(op.f('ix_Priority_level'), table_name='Priority')
    op.drop_index(op.f('ix_Priority_id'), table_name='Priority')
    op.drop_table('Priority')
    op.drop_index(op.f('ix_Category_id'), table_name='Category')
    op.drop_index(op.f('ix_Category_category_name'), table_name='Category')
    op.drop_table('Category')
    # ### end Alembic commands ###
