"""Add description to category table

Revision ID: eedb3c89236e
Revises: eb992de506b0
Create Date: 2026-02-04 14:39:52.469058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eedb3c89236e'
down_revision: Union[str, Sequence[str], None] = 'eb992de506b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Category', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_Category_description'), 'Category', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Category_description'), table_name='Category')
    op.drop_column('Category', 'description')
    # ### end Alembic commands ###
