"""Add PriorityLogs table

Revision ID: f81e1b6c9022
Revises: eedb3c89236e
Create Date: 2026-02-04 16:20:00.650302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81e1b6c9022'
down_revision: Union[str, Sequence[str], None] = 'eedb3c89236e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PredictionLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.Column('predicted_category_id', sa.Integer(), nullable=True),
    sa.Column('predicted_priority_id', sa.Integer(), nullable=True),
    sa.Column('confidence_category', sa.Float(), nullable=True),
    sa.Column('confidence_priority', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['Ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PredictionLog_confidence_category'), 'PredictionLog', ['confidence_category'], unique=False)
    op.create_index(op.f('ix_PredictionLog_confidence_priority'), 'PredictionLog', ['confidence_priority'], unique=False)
    op.create_index(op.f('ix_PredictionLog_id'), 'PredictionLog', ['id'], unique=False)
    op.create_index(op.f('ix_PredictionLog_input_text'), 'PredictionLog', ['input_text'], unique=False)
    op.create_index(op.f('ix_PredictionLog_model_name'), 'PredictionLog', ['model_name'], unique=False)
    op.create_index(op.f('ix_PredictionLog_predicted_category_id'), 'PredictionLog', ['predicted_category_id'], unique=False)
    op.create_index(op.f('ix_PredictionLog_predicted_priority_id'), 'PredictionLog', ['predicted_priority_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PredictionLog_predicted_priority_id'), table_name='PredictionLog')
    op.drop_index(op.f('ix_PredictionLog_predicted_category_id'), table_name='PredictionLog')
    op.drop_index(op.f('ix_PredictionLog_model_name'), table_name='PredictionLog')
    op.drop_index(op.f('ix_PredictionLog_input_text'), table_name='PredictionLog')
    op.drop_index(op.f('ix_PredictionLog_id'), table_name='PredictionLog')
    op.drop_index(op.f('ix_PredictionLog_confidence_priority'), table_name='PredictionLog')
    op.drop_index(op.f('ix_PredictionLog_confidence_category'), table_name='PredictionLog')
    op.drop_table('PredictionLog')
    # ### end Alembic commands ###
